AnimeNerdApp/Models/Anime.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace AnimeNerdApp.Models
{
    public class Anime
    {
        [Key]
        public int AnimeId { get; set; }
        [StringLength(100)]
        [Required]
        public string Name { get; set; }
        [StringLength(25)]
        public string Genre { get; set; }
        [Range(5,10)]
        [DisplayName("Husbandos")]
        public int NumberOfHusbandos { get; set; }
        [Range(1,300)]
        [DisplayName("Series Length")]
        public int NumberOfEpisodes { get; set; }
    }
}

AnimeNerdApp/Models/AnimeContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace AnimeNerdApp.Models
{
    public class AnimeContext : DbContext
    {

        public DbSet<Anime> Anime { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(
                @"Server=DESKTOP-4UGD5KM;Database=AnimeDb;Trusted_Connection=True;");
        }
    }
}

AnimeNerdApp/Models/ErrorViewModel.cs
using System;

namespace AnimeNerdApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AnimeNerdApp/Controllers/AnimesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AnimeNerdApp.Models;

namespace AnimeNerdApp.Controllers
{
    public class AnimesController : Controller
    {
        // GET: AnimesController
        public ActionResult Index()
        {
            List<Anime> result = null;
            using (AnimeContext context = new AnimeContext())
            {
                result = context.Anime.ToList();
            }
            return View(result);
        }

        

        // GET: AnimesController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AnimesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AnimesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                using (AnimeContext context = new AnimeContext())
                {
                    Anime anime = new Anime();
                    anime.Name = collection["Name"];
                    anime.Genre = collection["Genre"];
                    anime.NumberOfHusbandos = int.Parse(collection["NumberOfHusbandos"]);
                    anime.NumberOfEpisodes = int.Parse(collection["NumberOfEpisodes"]);

                    context.Anime.Update(anime);
                    context.SaveChanges();
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AnimesController/Edit/5
        public ActionResult Edit(int id)
        {
            Anime result = null;
            using(AnimeContext context = new AnimeContext())
            {
                result = context.Anime.Where(x => x.AnimeId == id).First();
            }
            return View(result);
        }

        // POST: AnimesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                using(AnimeContext context = new AnimeContext())
                {
                    Anime anime = context.Anime.Where(x => x.AnimeId == id).First();
                    anime.Name = collection["Name"];
                    anime.Genre = collection["Genre"];
                    anime.NumberOfHusbandos = int.Parse(collection["NumberOfHusbandos"]);
                    anime.NumberOfEpisodes = int.Parse(collection["NumberOfEpisodes"]);

                    context.Anime.Update(anime);
                    context.SaveChanges();
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Error");
            }
        }

        // GET: AnimesController/Delete/5
        public ActionResult Delete(int id)
        {
            Anime result = null;
            using (AnimeContext context = new AnimeContext())
            {
                result = context.Anime.Where(x => x.AnimeId == id).First();
            }
            return View(result);
        }

        // POST: AnimesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                using (AnimeContext context = new AnimeContext())
                {
                    Anime anime = context.Anime.Where(x => x.AnimeId == id).First();
                
                    context.Anime.Remove(anime);
                    context.SaveChanges();
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Error");
            }
        }
    }
}

AnimeNerdApp/Controllers/HomeController.cs
using AnimeNerdApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AnimeNerdApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            List<Anime> result = null;
            using (AnimeContext context = new AnimeContext())
            {
                result = context.Anime.ToList();
            }
            return View(result);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AnimeNerdApp/Views/Animes/Create.cshtml
@model AnimeNerdApp.Models.Anime

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Anime</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfHusbandos" class="control-label"></label>
                <input asp-for="NumberOfHusbandos" class="form-control" />
                <span asp-validation-for="NumberOfHusbandos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfEpisodes" class="control-label"></label>
                <input asp-for="NumberOfEpisodes" class="form-control" />
                <span asp-validation-for="NumberOfEpisodes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AnimeNerdApp/Views/Animes/Delete.cshtml
@model AnimeNerdApp.Models.Anime

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Anime</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfHusbandos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfHusbandos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfEpisodes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfEpisodes)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="AnimeId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AnimeNerdApp/Views/Animes/Edit.cshtml
@model AnimeNerdApp.Models.Anime

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Anime</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AnimeId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfHusbandos" class="control-label"></label>
                <input asp-for="NumberOfHusbandos" class="form-control" />
                <span asp-validation-for="NumberOfHusbandos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfEpisodes" class="control-label"></label>
                <input asp-for="NumberOfEpisodes" class="form-control" />
                <span asp-validation-for="NumberOfEpisodes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AnimeNerdApp/Views/Animes/Index.cshtml
@model IEnumerable<AnimeNerdApp.Models.Anime>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberOfHusbandos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberOfEpisodes)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberOfHusbandos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberOfEpisodes)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.AnimeId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.AnimeId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.AnimeId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

AnimeNerdApp/Views/Home/Index.cshtml
@model IEnumerable<Anime> 


@{
    ViewData["Title"] = "Home Page";
}

<h1 class="text-center">My Favorite Animes</h1>

AnimeNerdApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AnimeNerdApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AnimeNerdApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Animes" asp-action="Index">Animes</a>
                        </li>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AnimeNerdApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>